;;; -*- coding: utf-8 -*-
(("/Users/bo/Desktop/NodeTutorial/"
  (dired-filename . "/Users/bo/Desktop/NodeTutorial/package.json"))
 ("/Users/bo/Desktop/NodeTutorial/package.json" . 160)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/Preferences.el" . 7541)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Robust:Reliability-based Design Optimisation/Recherche biblio/"
  (dired-filename . "/Users/bo/Documents/Etudes/ENSAM 3A/Robust:Reliability-based Design Optimisation/Recherche biblio/JEL-Article.tex"))
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/Packages/elpa/auctex-11.88.8/tests/tex/" . 49)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/Packages/elpa/auctex-11.88.8/auctex-autoloads.el" . 10317)
 ("/Users/bo/Desktop/emacs.d/tabbar.el" . 71406)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/emacs.d/config_tabbar_aquamacs.el" . 4431)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/emacs.d/config_tabbar.el" . 2805)
 ("/Users/bo/Desktop/NodeTutorial/collectionDriver.js" . 1679)
 ("/Users/bo/Desktop/emacs~" . 1887)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Robust:Reliability-based Design Optimisation/Recherche biblio/Section1.tex" . 3028)
 ("/Users/bo/Desktop/emacs.d/themes/zenburn-theme.el" . 32037)
 ("/Users/bo/Downloads/node_tutorial_sample_app_complete/server/"
  (dired-filename . "/Users/bo/Downloads/node_tutorial_sample_app_complete/server/index.js"))
 ("/Users/bo/Downloads/node_tutorial_sample_app_complete/server/index.js" . 1290)
 ("/Users/bo/Desktop/NodeTutorial/index.js" . 3158)
 ("/Users/bo/Downloads/mongodb_sample_project1/"
  (dired-filename . "/Users/bo/Downloads/mongodb_sample_project1/package.json"))
 ("/Users/bo/Downloads/mongodb_sample_project1/package.json" . 156)
 ("/Users/bo/Desktop/NodeTutorial/views/data.jade" . 281)
 ("/Users/bo/Desktop/NodeTutorial/views/404.jade" . 56)
 ("/Users/bo/Desktop/NodeTutorial/public/hello.html" . 39)
 ("/Users/bo/.emacs.d/tabbar.el" . 1676)
 ("/Users/bo/.emacs~" . 11333)
 ("/Users/bo/.emacs.d/config_tabbar_aquamacs.el" . 4432)
 ("/Users/bo/.emacs.d/config_tabbar.el" . 6559)
 ("/Users/bo/.emacs.aquamacs" . 4705)
 ("/Users/bo/Desktop/obenchekroun.github.io/projects/SimpleMCChat/DEBIAN/control" . 323)
 ("/Users/bo/.bash_profile" . 1513)
 ("/Users/bo/.bash_prompt" . 2794)
 ("/Users/bo/.aliases" . 5858)
 ("/Users/bo/.exports" . 915)
 ("/Users/bo/.functions" . 7259)
 ("/Users/bo/ldid/make.sh" . 68)
 ("/Users/bo/Code/configUnix/bootstrap.sh" . 185)
 ("/Users/bo/Code/configUnix/.bash_prompt" . 2979)
 ("/Users/bo/Code/configUnix/.bashrc" . 41)
 ("/Users/bo/Code/configUnix/.bash_profile" . 1310)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/PresentationMemoire/slides.tex" . 877)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/PresentationMemoire/beamerthemehsrm.sty" . 3727)
 ("/Users/bo/Desktop/SimpleMCChat/README.md" . 1767)
 ("/Users/bo/Desktop/obenchekroun.github.io/depictions/com.bo.SimpleMCChat/info.xml" . 561)
 ("/Users/bo/Desktop/obenchekroun.github.io/Packages" . 629)
 ("/Users/bo/Desktop/obenchekroun.github.io/README.md" . 2315)
 ("/Users/bo/Desktop/obenchekroun.github.io/gpush.sh" . 14)
 ("/Users/bo/Desktop/obenchekroun.github.io/update.sh" . 12)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Robust:Reliability-based Design Optimisation/Recherche biblio/Makefile" . 1159)
 ("/Users/bo/Desktop/SimpleMCChat/gpush.sh" . 261)
 ("/Users/bo/Desktop/finished.rb" . 879)
 ("/Users/bo/Desktop/obenchekroun.github.io/packages.sh" . 89)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/RPS/RapportRPS/Makefile" . 61)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/PresentationMemoire/"
  (dired-filename . "/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/PresentationMemoire/Makefile"))
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/PresentationMemoire/Makefile" . 91)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Presoutenance/Presentation/"
  (dired-filename . "/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Presoutenance/Presentation/Makefile"))
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Presoutenance/Presentation/Makefile" . 1259)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Presoutenance/"
  (dired-filename . "/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Presoutenance/Makefile"))
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Presoutenance/Makefile" . 1150)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Big Data en Management Science/"
  (dired-filename . "/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Big Data en Management Science/Makefile"))
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Big Data en Management Science/Makefile" . 116)
 ("/Users/bo/Desktop/obenchekroun.github.io/index.html" . 508)
 ("/Users/bo/.Trash/com.decimation.impossibletrianglelockglyph/info.xml" . 487)
 ("/Users/bo/Desktop/obenchekroun.github.io/projects/FBIcon/DEBIAN/control" . 212)
 ("/Users/bo/Desktop/com.bo.simplemcchat/info.xml" . 302)
 ("/Users/bo/Desktop/obenchekroun.github.io/depictions/com.bo.SimpleMCChat/changelog.xml" . 74)
 ("/Users/bo/Desktop/obenchekroun.github.io/depictions/index.html" . 3626)
 ("/Users/bo/Desktop/obenchekroun.github.io/depictions/com.bo.FBIcon/info.xml" . 47)
 ("/Users/bo/Desktop/decimation.github.io-master/Packages" . 498)
 ("/Users/bo/Desktop/decimation.github.io-master/depictions/com.decimation.lowerlte/info.xml" . 1000)
 ("/Users/bo/Desktop/obenchekroun.github.io/depictions/screenshots.html" . 1451)
 ("/Users/bo/Desktop/obenchekroun.github.io/"
  (dired-filename . "/Users/bo/Desktop/obenchekroun.github.io/README.md"))
 ("/Users/bo/Desktop/decimation.github.io-master/depictions/index.html" . 1261)
 ("/Users/bo/Desktop/decimation.github.io-master/depictions/screenshots.html" . 1451)
 ("/Users/bo/Desktop/decimation.github.io-master/README.md" . 165)
 ("/Users/bo/Desktop/obenchekroun.github.io/projects/SimpleMCChat/DEBIAN/postrm" . 192)
 ("/Users/bo/Desktop/obenchekroun.github.io/projects/SimpleMCChat/DEBIAN/preinst" . 192)
 ("/Users/bo/Desktop/obenchekroun.github.io/remove.sh" . 94)
 ("/Users/bo/Desktop/obenchekroun.github.io/projects/infiniloader/DEBIAN/control" . 35)
 ("/Users/bo/Downloads/MCDemo/MCDemo.xcodeproj/project.pbxproj" . 10580)
 ("/Users/bo/Code/Programmation/Algorithme résolution le compte est bon/Makefile" . 109)
 ("/Users/bo/Code/Programmation/Algorithme résolution le compte est bon/compte.c" . 5130)
 ("/Users/bo/Code/Programmation/Algorithme résolution le compte est bon/compte2.c" . 7707)
 ("/Users/bo/Desktop/Pokemon ROM Hacked/Pokemon Games/Blaze Black & Volt White, Version 3.1/Documentation/Item & Trade Changes.txt" . 1144)
 ("/Users/bo/Code/configUnix/brew.sh" . 950)
 ("/Users/bo/.bash_profile~" . 860)
 ("/Users/bo/Code/Caractéristiques:config système/Fichiers couche Unix/Historiques shell/bash_history.2" . 12481)
 ("/Users/bo/Code/configUnix/.aliases" . 4357)
 ("/Users/bo/Code/Scripts shell/colorTerm.sh" . 151)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Mémoire de recherche/Big Data en Management Science/Management-Science.tex" . 2507)
 ("/Users/bo/Code/configUnix/Theme terminal/"
  (dired-filename . "/Users/bo/Code/configUnix/Theme terminal/.DS_Store"))
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/aquamacs-emacs-starter-kit/init.el" . 1169)
 ("/Users/bo/Code/configUnix/README.txt" . 94)
 ("/Users/bo/dotfiles/bootstrap.sh" . 236)
 ("/Users/bo/dotfiles/.osx" . 27751)
 ("/Users/bo/dotfiles/.bash_profile" . 636)
 ("/Users/bo/dotfiles/.bash_prompt" . 172)
 ("/Users/bo/Desktop/dotfilesTEST/brew.sh" . 1250)
 ("/Users/bo/dotfiles/In ~:Library:Preferences:Aquamacs Emacs/Preferences.el" . 1809)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/places.el" . 2617)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/Packages/SessionDesktop.el" . 3091)
 ("/Users/bo/Downloads/osx" . 19378)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Allouche/Allouche/p1.tex" . 1197)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Allouche/Allouche/p3.tex" . 1067)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Allouche/Allouche/Makefile" . 618)
 ("/Users/bo/Desktop/3A/Mémoire de recherche/Big Data en Management Science/" . 276)
 ("/Users/bo/Desktop/3A/Mémoire de recherche/PresentationMemoire/slides.tex" . 2224)
 ("/Users/bo/Desktop/3A/Mémoire de recherche/PresentationMemoire/Makefile" . 1360)
 ("/Users/bo/Desktop/3A/Mémoire de recherche/PresentationMemoire/" . 85)
 ("/Users/bo/Desktop/Big Data en Management Science/Management-Science.tex" . 3629)
 ("/Users/bo/Desktop/PresentationMemoire/slides.tex" . 1512)
 ("/Users/bo/Desktop/PresentationMemoire/beamerthemehsrm.sty" . 1365)
 ("/Users/bo/Desktop/Big Data en Management Science/" . 252)
 ("/Users/bo/Desktop/Mémoire de recherche/" . 237)
 ("/Users/bo/Desktop/PresentationMemoire/_region_.tex" . 22685)
 ("/Users/bo/Desktop/Big Data en Management Science/Section5.tex" . 3137)
 ("/Users/bo/Desktop/Big Data en Management Science/Section4.tex" . 879)
 ("/Users/bo/Desktop/Big Data en Management Science/Section3.tex" . 16571)
 ("/Users/bo/Desktop/Big Data en Management Science/Section2.tex" . 8234)
 ("/Users/bo/Desktop/Big Data en Management Science/Section1.tex" . 7803)
 ("/Users/bo/Desktop/PresentationMemoire/Makefile" . 59)
 ("/Users/bo/Desktop/Big Data en Management Science/Intro.tex" . 48)
 ("/Users/bo/Desktop/Big Data en Management Science/Makefile" . 84)
 ("/Users/bo/Desktop/BigDataRapport/Section2.tex" . 8512)
 ("/Users/bo/Desktop/BigDataRapport/Section5.tex" . 6967)
 ("/Users/bo/Desktop/BigDataRapport/Conclusion.tex" . 41)
 ("/Users/bo/Desktop/BigDataRapport/JEL-Article.tex" . 3919)
 ("/Users/bo/Desktop/BigDataRapport/Section4.tex" . 21041)
 ("/Users/bo/Desktop/dsaz.bib" . 627)
 ("/Users/bo/Desktop/BigDataRapport/biblio.bib" . 133629)
 ("/Users/bo/Desktop/BigDataRapport/Section3.tex" . 15498)
 ("/Users/bo/Desktop/3A/Robust:Reliability-based Design Optimisation/Recherche biblio/Section1.tex" . 14219)
 ("/Users/bo/Desktop/3A/Robust:Reliability-based Design Optimisation/Recherche biblio/Section2.tex" . 299)
 ("/Users/bo/Desktop/3A/Robust:Reliability-based Design Optimisation/Recherche biblio/Section3.tex" . 1847)
 ("/Users/bo/Desktop/plan mémoire" . 1021)
 ("/Users/bo/Desktop/BigDataRapport/Section1.tex" . 5262)
 ("/Users/bo/Desktop/BigDataRapport/Intro.tex" . 5406)
 ("/Users/bo/Desktop/BigDataRapport/Makefile" . 70)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p2.tex" . 33)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p3.tex" . 8264)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p4.tex" . 23)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/rapport.tex" . 591)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/Makefile" . 93)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/" . 908)
 ("/Users/bo/Desktop/3A/Robust:Reliability-based Design Optimisation/Recherche biblio/" . 289)
 ("/Users/bo/Desktop/3A/Allouche/Allouche en jel/rapport.tex" . 1986)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/images/" . 255)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/Presentation/slides.tex" . 165)
 ("/Users/bo/Code/iOS/Transformation contacts pour iPhone.scpt" . 1177)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/tabbar-window.el" . 3516)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/aquamacs-emacs-starter-kit/README.markdown" . 4147)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/aquamacs-tabbar.el" . 35576)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/tabbar-window~.el" . 36678)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/revive.el" . 39006)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/tabbar.el" . 72695)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/aquamacs-tabbar.el.back.el" . 17642)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/aquamacs-tabbar~.el" . 35814)
 ("/Users/bo/.emacs" . 4395)
 ("/Users/bo/Desktop/dvipdfmx.cfg" . 1141)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p1.tex" . 66)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p5.tex" . 30)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p2.tex" . 765)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/_region_.tex" . 520))
