;;; -*- coding: utf-8 -*-
(("/Users/bo/Library/Preferences/Aquamacs Emacs/Preferences.el" . 1809)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/customizations.el" . 1431)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/places.el" . 2617)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/Packages/SessionDesktop.el" . 3091)
 ("/Users/bo/Downloads/osx" . 19378)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Allouche/Allouche/p1.tex" . 1197)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Allouche/Allouche/p3.tex" . 1067)
 ("/Users/bo/Documents/Etudes/ENSAM 3A/Allouche/Allouche/Makefile" . 618)
 ("/Users/bo/Desktop/3A/Mémoire de recherche/Big Data en Management Science/" . 276)
 ("/Users/bo/Desktop/3A/Mémoire de recherche/PresentationMemoire/slides.tex" . 2224)
 ("/Users/bo/Desktop/3A/Mémoire de recherche/PresentationMemoire/Makefile" . 1360)
 ("/Users/bo/Desktop/3A/Mémoire de recherche/PresentationMemoire/" . 85)
 ("/Users/bo/Desktop/Big Data en Management Science/Management-Science.tex" . 3629)
 ("/Users/bo/Desktop/PresentationMemoire/slides.tex" . 1512)
 ("/Users/bo/Desktop/PresentationMemoire/beamerthemehsrm.sty" . 1365)
 ("/Users/bo/Desktop/Big Data en Management Science/" . 252)
 ("/Users/bo/Desktop/Mémoire de recherche/" . 237)
 ("/Users/bo/Desktop/PresentationMemoire/_region_.tex" . 22685)
 ("/Users/bo/Desktop/Big Data en Management Science/Section5.tex" . 3137)
 ("/Users/bo/Desktop/Big Data en Management Science/Section4.tex" . 879)
 ("/Users/bo/Desktop/Big Data en Management Science/Section3.tex" . 16571)
 ("/Users/bo/Desktop/Big Data en Management Science/Section2.tex" . 8234)
 ("/Users/bo/Desktop/Big Data en Management Science/Section1.tex" . 7803)
 ("/Users/bo/Desktop/PresentationMemoire/Makefile" . 59)
 ("/Users/bo/Desktop/Big Data en Management Science/Intro.tex" . 48)
 ("/Users/bo/Desktop/Big Data en Management Science/Makefile" . 84)
 ("/Users/bo/Desktop/BigDataRapport/Section2.tex" . 8512)
 ("/Users/bo/Desktop/BigDataRapport/Section5.tex" . 6967)
 ("/Users/bo/Desktop/BigDataRapport/Conclusion.tex" . 41)
 ("/Users/bo/Desktop/BigDataRapport/JEL-Article.tex" . 3919)
 ("/Users/bo/Desktop/BigDataRapport/Section4.tex" . 21041)
 ("/Users/bo/Desktop/dsaz.bib" . 627)
 ("/Users/bo/Desktop/BigDataRapport/biblio.bib" . 133629)
 ("/Users/bo/Desktop/BigDataRapport/Section3.tex" . 15498)
 ("/Users/bo/Desktop/3A/Robust:Reliability-based Design Optimisation/Recherche biblio/Section1.tex" . 14219)
 ("/Users/bo/Desktop/3A/Robust:Reliability-based Design Optimisation/Recherche biblio/Section2.tex" . 299)
 ("/Users/bo/Desktop/3A/Robust:Reliability-based Design Optimisation/Recherche biblio/Section3.tex" . 1847)
 ("/Users/bo/Desktop/plan mémoire" . 1021)
 ("/Users/bo/Desktop/BigDataRapport/Section1.tex" . 5262)
 ("/Users/bo/Desktop/BigDataRapport/Intro.tex" . 5406)
 ("/Users/bo/Desktop/BigDataRapport/Makefile" . 70)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p2.tex" . 33)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p3.tex" . 8264)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p4.tex" . 23)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/rapport.tex" . 591)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/Makefile" . 93)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/" . 908)
 ("/Users/bo/.emacs~" . 10769)
 ("/Users/bo/.emacs.d/config_tabbar_aquamacs.el" . 411)
 ("/Users/bo/Desktop/3A/Robust:Reliability-based Design Optimisation/Recherche biblio/" . 289)
 ("/Users/bo/Desktop/3A/Allouche/Allouche en jel/rapport.tex" . 1986)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/images/" . 255)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/Presentation/slides.tex" . 165)
 ("/Users/bo/Code/iOS/Transformation contacts pour iPhone.scpt" . 1177)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/tabbar-window.el" . 3516)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/aquamacs-emacs-starter-kit/README.markdown" . 4147)
 ("/Users/bo/Library/Preferences/Aquamacs Emacs/aquamacs-emacs-starter-kit/init.el" . 3241)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/aquamacs-tabbar.el" . 35576)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/tabbar-window~.el" . 36678)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/revive.el" . 39006)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/tabbar.el" . 72695)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/aquamacs-tabbar.el.back.el" . 17642)
 ("/Users/bo/.emacs.d/config_tabbar.el" . 905)
 ("/Applications/Aquamacs.app/Contents/Resources/lisp/aquamacs/tabbar/aquamacs-tabbar~.el" . 35814)
 ("/Users/bo/.emacs" . 4395)
 ("/Users/bo/Desktop/dvipdfmx.cfg" . 1141)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p1.tex" . 66)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p5.tex" . 30)
 ("/Users/bo/.emacs.d/tabbar.el" . 23022)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/p2.tex" . 765)
 ("/Users/bo/Desktop/Mémoire de recherche/Presoutenance/_region_.tex" . 520))
